In [3]:
pip install numpy

In [1]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])

In [2]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(arr.ndim)


2


In [5]:
print(arr.shape)

(2, 3)


In [7]:
a=np.array([[1,2,3],[9,8,7]], dtype='float')
print(a)

[[1. 2. 3.]
 [9. 8. 7.]]


In [9]:
print(type(a))


<class 'numpy.ndarray'>


In [11]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.linspace?


Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x0000027C5F393E20>
File:            e:\anaconda\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
 

In [23]:
d=np.array([[1,6,8,4],[9,5,7,6],[5,8,7,3]])
new=d.reshape([2,2,3])
print(new)

[[[1 6 8]
  [4 9 5]]

 [[7 6 5]
  [8 7 3]]]


In [24]:
d=np.array([[1,6,8,4],[9,5,7,6],[5,8,7,3],[9,6,5,7]])


In [28]:
print(d[1:,:3])

[[9 5 7]
 [5 8 7]
 [9 6 5]]


In [29]:
f=np.array([[5,8,1,3]])
print(f+1)

[[6 9 2 4]]


In [30]:
print(f*2)

[[10 16  2  6]]
