# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [9]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [10]:
print(np.__version__)
print(np.show_config())

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: E:/Anaconda/Library/include
    lib directory: E:/Anaconda/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: E:/Anaconda/Library/include
    lib directory: E:/Anaconda/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build

#### 3. Create a null vector of size 10

In [11]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [12]:
arr=np.array([5,6,2,7,8,3,1,5])
print(arr.size * arr.itemsize)

64


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [13]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            e:\anaconda\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be s

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [14]:
new_arr = np.zeros(10)
new_arr[4] = 1
print(new_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [15]:
range = np.arange(10,50)
print(range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [16]:
np.flip(range)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
np.matrix([[0,1,2],[3,4,5],[6,7,8]])

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [18]:
np.arange(0,9).reshape(3,3,order='F')

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [19]:
cd=np.array([1,2,0,0,4,0])
np.nonzero(cd)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [21]:
from numpy.random import randn
np.random.seed(101)
np.array([[randn(3)],[randn(3)],[randn(3)]])

array([[[ 2.70684984,  0.62813271,  0.90796945]],

       [[ 0.50382575,  0.65111795, -0.31931804]],

       [[-0.84807698,  0.60596535, -2.01816824]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [22]:
k=np.array([[randn(10)],[randn(10)]])
print(k)
print("Maximum is ",np.max(k))
print("Minimum is ",np.min(k))

[[[ 0.74012206  0.52881349 -0.58900053  0.18869531 -0.75887206
   -0.93323722  0.95505651  0.19079432  1.97875732  2.60596728]]

 [[ 0.68350889  0.30266545  1.69372293 -1.70608593 -1.15911942
   -0.13484072  0.39052784  0.16690464  0.18450186  0.80770591]]]
Maximum is  2.60596727979128
Minimum is  -1.7060859307350775


#### 14. Create a random vector of size 30 and find the mean value

In [23]:
p = np.array(randn(30))
print(p)
print("Mean Value is ",np.mean(p))

[ 7.29596753e-02  6.38787013e-01  3.29646299e-01 -4.97104023e-01
 -7.54069701e-01 -9.43406403e-01  4.84751647e-01 -1.16773316e-01
  1.90175480e+00  2.38126959e-01  1.99665229e+00 -9.93263500e-01
  1.96799505e-01 -1.13664459e+00  3.66479606e-04  1.02598415e+00
 -1.56597904e-01 -3.15791439e-02  6.49825833e-01  2.15484644e+00
 -6.10258856e-01 -7.55325340e-01 -3.46418504e-01  1.47026771e-01
 -4.79448039e-01  5.58769406e-01  1.02481028e+00 -9.25874259e-01
  1.86286414e+00 -1.13381716e+00]
Mean Value is  0.14677969793380555


#### 15. Create a 2d array with 1 on the border and 0 inside

In [24]:
twod = np.array([[1,1,1],[1,0,1],[1,1,1]])
print(twod)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [25]:
s=(3,3)
twod = np.ones(s)
twod[1,1]=0
print(twod)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [95]:
t=np.ones((3,3))
t[0::2,::]=0
t[1,::2]=0
print(t)

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [84]:
nan
False
False
nan
True
False

True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [82]:
i=np.zeros((5,5))
i[1,0]=1
i[2,1]=2
i[3,2]=3
i[4,3]=4
print(i)
print(np.diag(1+np.arange(4),k=-1))

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [50]:
a =np.zeros((8,8))
a[::2,1::2]=1
a[1::2,::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [63]:
a = np.ndarray((6,7,8))
print(a[2,2,3])

4.272556019931051e+180


In [76]:
print(np.unravel_index(100,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))
